import type { Metadata } from "next"
import localfont from "next/font/local"

import "./globals.css"

export const metadata:Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const druk = localfont({
  src:[
    {
      path:"./fonts/PlusJakartaSans-Medium.ttf",
      weight:"700"
    }
  ],
  variable:"--font-druk"
})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${druk.variable}`} >
      <body>{children}</body>
    </html>
  )
}
